# Dependabot configuration
#
# For more information, please refer to:
#   https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2

updates:

# Maintain dependencies for GitHub Actions
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
