name: Merge Elastic updates

on:
  workflow_run:
    workflows: [ CI ]
    types:
      - completed
    branches:
      - update/main
      - update/tls
      - update/release-7.x

jobs:

  merge:
    name: Merge pull request
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Impersonate update bot
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Approve and merge
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_LOGIN: docker-elk-updater
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Delete branch
        uses: actions/github-script@v6
        with:
          script: |
            await github.request('DELETE /repos/{owner}/{repo}/git/refs/{ref}', {
              owner: '${{ github.event.workflow_run.repository.owner.login }}',
              repo: '${{ github.event.workflow_run.repository.name }}',
              ref: 'heads/${{ github.event.workflow_run.head_branch }}'
            })
