// Code generated by MockGen. DO NOT EDIT.
// Source: car.go

// Package structs is a generated GoMock package.
package structs

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStarter is a mock of Starter interface.
type MockStarter struct {
	ctrl     *gomock.Controller
	recorder *MockStarterMockRecorder
}

// MockStarterMockRecorder is the mock recorder for MockStarter.
type MockStarterMockRecorder struct {
	mock *MockStarter
}

// NewMockStarter creates a new mock instance.
func NewMockStarter(ctrl *gomock.Controller) *MockStarter {
	mock := &MockStarter{ctrl: ctrl}
	mock.recorder = &MockStarterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStarter) EXPECT() *MockStarterMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockStarter) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockStarterMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockStarter)(nil).Start))
}
